# Generated by Django 5.1.5 on 2025-02-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_student_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="mail",
            new_name="email",
        ),
    ]
